### ISSUE TITLE
I have NO idea how to use this package

### ISSUE THREAD

**Issue by yscialom** [jdthorpe/ajvpy#1]
What is the minimal requirement to use this package? Do I need nodejs? Do I need ajv? Do I need anything else? Please clarify how to use it from scratch.

**Comment by jdthorpe** [comment]
This package hasn't been touched in 6 years and it depends on a package that hasn't been updated in 14 years, so the chances that it no longer works are high.  

Back in the day,  you needed python and node installed, and package installation was something like: 

```sh
# install the node packages
npm install

# install py v8
pip install pyv8 
```

and then clone this repo and make sure this package was on Python's search path.  I never went down the formal python packaging. (e.g. `setup.py`).  I was just having fun with esoteric multi-language things...
